### ISSUE TITLE
Add some best problems on Binary Tree

### ISSUE THREAD

**Issue by IEEE-IIITSricity** [IEEE-IIITSricity/DS-ALGO#4]

**Comment by Kajalkare17** [comment]
I would like to add some tree problems

**Comment by ishi0301** [comment]
I would like to do this in C++

**Comment by AparnaJuhi** [comment]
I want to add some good Questions on cp asked in interviews of Tier 1 company

**Comment by Surajkumar573** [comment]
I would like to work on it.

**Comment by Riya-code** [comment]
I would like to take it.

**Comment by guptaa98** [comment]
I would like to contribute!

**Comment by Rubal-MB** [comment]
I would like to contribute .

**Comment by Vaibhav22-Dev** [comment]
I would like to implement replace each node in binarytree with sum of its inorder predecessor and succesor , it is a question 
asked in adobe. with your permission , can i implement
