### ISSUE TITLE
Add stack DataStructure

### ISSUE THREAD

**Issue by IEEE-IIITSricity** [IEEE-IIITSricity/DS-ALGO#5]

**Comment by AparnaJuhi** [comment]
I want to work on this issue. Please assign it to me

**Comment by lucifer79gg** [comment]
I would love to work on Data Structures. Please assign it to me.

**Comment by sai-koushik-macha** [comment]
I would like to work on this by adding stack data structure in c and by adding post fix. So, please assign me

**Comment by guruc-134** [comment]
i would like to work on it . please assign it to me

**Comment by Vaibhav22-Dev** [comment]
As we know selection sort is unstable sort , i.e it might change the occurance of two similar elements ,. So I would like to implement selection sort as stable selection sort using linked-list. with your permission if anyone has not done this yet, I am waiting for your reply
